Repository hmcts/fis-hmc-api, pull requests merged in 2024-05, with the labels that each got.

#345 funtional test cases
  src/functionalTest/java/uk/gov/hmcts/reform/hmc/api/controllers/HearingsContFunctionalTest.java
  src/functionalTest/resources/requests/automated-hearing-request.json
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/api/controllers/HearingsControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/api/utils/TestConstants.java
  src/integrationTest/resources/requests/automated-hearing-request.json
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-hmc-api-pr-345

#342 FPET-951
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-hmc-api-pr-342

#344 Prl 5476 testcase
  build.gradle
  src/main/java/uk/gov/hmcts/reform/hmc/api/model/ccd/CaseData.java
  src/main/java/uk/gov/hmcts/reform/hmc/api/model/ccd/HearingData.java
  src/main/java/uk/gov/hmcts/reform/hmc/api/model/response/HearingResponse.java
  src/main/java/uk/gov/hmcts/reform/hmc/api/services/HearingsServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/hmc/api/services/AutomateHearingServiceTest.java
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-hmc-api-pr-344

#366 FPET-967: updated readme
  Jenkinsfile_nightly
  README.md
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-hmc-api-pr-366

#367 FPET-967: updated cron job
  Jenkinsfile_nightly
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-hmc-api-pr-367

#372 Fpet 967
  Jenkinsfile_nightly
Labels: ns:fis, prd:fis, rel:fis-hmc-api-pr-372

#376 Fpet 967
  Jenkinsfile_nightly
Labels: ns:fis, prd:fis, rel:fis-hmc-api-pr-376

#377 Fpet 967
  build.gradle
Labels: ns:fis, prd:fis, rel:fis-hmc-api-pr-377

#382 Fpet 967
  Jenkinsfile_nightly
  build.gradle
  src/main/java/uk/gov/hmcts/reform/hmc/api/restclient/ServiceAuthorisationTokenApi.java
  src/test/java/uk/gov/hmcts/reform/hmc/api/controllers/HearingsControllerTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/api/controllers/RootControllerTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/api/services/RefDataServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/api/services/RoleAssignmentServiceTest.java
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-hmc-api-pr-382, aat/no-changes, prod/no-changes

#394 Fpet 967
  Jenkinsfile_nightly
  src/test/java/uk/gov/hmcts/reform/hmc/api/controllers/HearingsControllerTest.java
Labels: ns:fis, prd:fis, enable_keep_helm, aat/no-changes, prod/no-changes, rel:fis-hmc-api-pr-394

#395 FPET-967: added fortify release id
  build.gradle
  config/fortify-client.properties
Labels: enable_keep_helm

#396 FPET-967: added forify vault parameter
  Jenkinsfile_nightly
Labels: ns:fis, prd:fis, aat/no-changes, prod/no-changes, rel:fis-hmc-api-pr-396

#398 FPET-967: added non root user in docker
  Dockerfile
Labels: ns:fis, prd:fis, aat/no-changes, prod/no-changes, rel:fis-hmc-api-pr-398

#353 Allowing HMC service update to be called only when required
  build.gradle
  src/main/java/uk/gov/hmcts/reform/hmc/api/config/ServiceBusConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/api/controllers/HearingsController.java
  src/main/java/uk/gov/hmcts/reform/hmc/api/services/HearingsService.java
  src/main/java/uk/gov/hmcts/reform/hmc/api/services/HearingsServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/hmc/api/utils/Constants.java
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-hmc-api-pr-353
